name: Docker Image CI

on:
  push:
    branches:
      - main  # 推送main分支时触发
      - github-runner
    tags:
      - 'v*.*.*'  # 只在以 v 开头的标签推送时触发，例如 v1.0.0
  workflow_dispatch:

jobs:
  release:
    name: Release Docker images
    runs-on: self-hosted
    env:
      no_proxy: localhost,127.0.0.1,::1
      https_proxy: http://127.0.0.1:7890
      http_proxy: http://127.0.0.1:7890
      all_proxy: socks5h://127.0.0.1:7890
      HTTP_PROXY: http://127.0.0.1:7890
      HTTPS_PROXY: http://127.0.0.1:7890
    permissions:
      packages: write
      contents: write
      id-token: write
      issues: write
    steps:
      - name: Check Disk Space
        run: |
          df -h
          docker system df

      - name: Clean up Docker resources
        run: |
          docker system prune -af
          docker builder prune -af

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from tag
        id: get_version
        run: |
          if [[ "$GITHUB_REF" =~ ^refs/tags/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            echo "VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
            echo "IS_VERSION=true" >> $GITHUB_ENV
          else
            echo "VERSION=latest" >> $GITHUB_ENV
            echo "IS_VERSION=false" >> $GITHUB_ENV
          fi

      # 构建 xiaozhi-server 镜像
      - name: Build and push xiaozhi-server
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile-server
          push: true
          tags: |
            r-veen.volces.com/vei/public/xiaozhi-server:api
          platforms: linux/amd64
          build-args: |
            HTTP_PROXY=${{ env.HTTP_PROXY }}
            HTTPS_PROXY=${{ env.HTTPS_PROXY }}

      # 构建 manager-api 镜像
      - name: Build and push manager-web
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile-web
          push: true
          tags: |
            r-veen.volces.com/vei/public/xiaozhi-server:web
          platforms: linux/amd64
          build-args: |
            HTTP_PROXY=${{ env.HTTP_PROXY }}
            HTTPS_PROXY=${{ env.HTTPS_PROXY }}

  restart:
    name: Release Docker images
    runs-on: self-hosted
    needs: release
    permissions:
      packages: write
      contents: write
      id-token: write
      issues: write
    steps:
      - name: Restart docker compose
        id: restart-service
        run: |
          cd /root/xiaozhi-esp32-server/
          docker-compose up -d