name: Docker Image CI

on:
  push:
    branches:
      - main  # 推送main分支时触发
      - github-runner

    tags:
      - 'v*.*.*'  # 只在以 v 开头的标签推送时触发，例如 v1.0.0
  workflow_dispatch:

jobs:
  release:
    name: Release Docker images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write
      issues: write
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Check Disk Space
        run: |
          df -h
          docker system df

      - name: Clean up Docker resources
        run: |
          docker system prune -af

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        env:
          DOCKER_CLIENT_TIMEOUT: 120  # 超时时间（秒）
          COMPOSE_HTTP_TIMEOUT: 120
        with:
          registry: r-veen.volces.com
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SECRET }}
          debug: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from tag
        id: get_version
        run: |
          if [[ "$GITHUB_REF" =~ ^refs/tags/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            echo "VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
            echo "VERSION=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
            echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
          fi

      # 构建 xiaozhi-server 镜像
      - name: Build and push xiaozhi-server
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile-server
          network: host
          push: true
          tags: |
            r-veen.volces.com/vei/public/xiaozhi-server-api:${{ env.VERSION }}
          platforms: linux/amd64

      # 构建 manager-api 镜像
      - name: Build and push manager-web
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile-web
          network: host
          push: true
          tags: |
            r-veen.volces.com/vei/public/xiaozhi-server-web:${{ env.VERSION }}
          platforms: linux/amd64

  deploy:
    name: Deploy Docker images
    runs-on: self-hosted
    needs: release
    if: github.ref == 'refs/heads/main'
    permissions:
      packages: write
      contents: write
      id-token: write
      issues: write
    steps:
      - name: Restart docker compose
        id: restart-service
        run: |
          cd /root/xiaozhi-esp32-server/
          sed -i "s/xiaozhi-server-api:.*/xiaozhi-server-api:${{ needs.release.outputs.VERSION }}/g" docker-compose.yaml
          sed -i "s/xiaozhi-server-web:.*/xiaozhi-server-web:${{ needs.release.outputs.VERSION }}/g" docker-compose.yaml
          docker-compose up -d